/**
 * Generates supabase/seed.sql from the mock catalog in src/lib/data.
 * Run: npm run db:seed-sql   then paste supabase/seed.sql into the Supabase SQL Editor.
 * The seed is idempotent (safe to run more than once).
 */
import { writeFileSync } from "node:fs";
import { categories } from "../src/lib/data/categories";
import { products } from "../src/lib/data/products";

const q = (v: string | number | null | undefined) =>
  v === null || v === undefined ? "null" : typeof v === "number" ? String(v) : `'${v.replace(/'/g, "''")}'`;

const out: string[] = ["-- GENERATED by scripts/generate-seed.ts. Do not edit by hand.", "begin;", ""];

out.push("-- categories");
categories.forEach((c, i) => {
  out.push(
    `insert into public.categories (name, slug, image_url, sort_order) values (${q(c.name)}, ${q(c.slug)}, ${q(c.image)}, ${i}) ` +
      `on conflict (slug) do update set name = excluded.name, image_url = excluded.image_url, sort_order = excluded.sort_order;`,
  );
});

out.push("", "-- products");
for (const p of products) {
  out.push(
    `insert into public.products (category_id, name, slug, description, origin, badge, badge_tone) ` +
      `select id, ${q(p.name)}, ${q(p.slug)}, ${q(p.description)}, ${q(p.origin)}, ${q(p.badge?.text)}, ${q(p.badge?.tone)} ` +
      `from public.categories where slug = ${q(p.categorySlug)} ` +
      `on conflict (slug) do update set name = excluded.name, description = excluded.description, ` +
      `origin = excluded.origin, badge = excluded.badge, badge_tone = excluded.badge_tone;`,
  );
}

out.push("", "-- variants (stock is only set on first insert so re-seeding never resets live stock)");
for (const p of products) {
  for (const v of p.variants) {
    out.push(
      `insert into public.product_variants (product_id, label, sku, price_kobo, compare_at_price_kobo, stock_qty, max_per_order) ` +
        `select id, ${q(v.label)}, ${q(v.sku)}, ${v.priceKobo}, ${q(v.compareAtPriceKobo)}, ${v.stockQty}, ${v.maxPerOrder} ` +
        `from public.products where slug = ${q(p.slug)} ` +
        `on conflict (sku) do update set label = excluded.label, price_kobo = excluded.price_kobo, ` +
        `compare_at_price_kobo = excluded.compare_at_price_kobo, max_per_order = excluded.max_per_order;`,
    );
  }
}

out.push("", "-- images (replaced wholesale per product)");
for (const p of products) {
  out.push(`delete from public.product_images where product_id = (select id from public.products where slug = ${q(p.slug)});`);
  p.images.forEach((url, i) => {
    out.push(
      `insert into public.product_images (product_id, url, alt, sort_order) ` +
        `select id, ${q(url)}, ${q(p.name)}, ${i} from public.products where slug = ${q(p.slug)};`,
    );
  });
}

out.push("", "-- related products");
for (const p of products) {
  for (const r of p.relatedSlugs) {
    out.push(
      `insert into public.product_related (product_id, related_product_id) ` +
        `select a.id, b.id from public.products a, public.products b where a.slug = ${q(p.slug)} and b.slug = ${q(r)} ` +
        `on conflict do nothing;`,
    );
  }
}

out.push(
  "",
  "-- shipping methods (PLACEHOLDER prices/cut-offs: confirm with the owner, then edit in the dashboard)",
  "insert into public.shipping_methods (name, price_kobo, free_above_kobo, eta_text, cutoff_time, sort_order)",
  "select * from (values",
  "  ('Same-day express', 250000, 3500000, 'Delivered today (order before the cut-off)', time '12:00', 1),",
  "  ('Next-day delivery', 150000, 3500000, 'Delivered tomorrow', time '18:00', 2),",
  "  ('Self-pickup', 0, null::int, 'Ready for pickup (location to be confirmed)', null::time, 3)",
  ") as v(name, price_kobo, free_above_kobo, eta_text, cutoff_time, sort_order)",
  "where not exists (select 1 from public.shipping_methods);",
  "",
  "commit;",
  "",
);

writeFileSync("supabase/seed.sql", out.join("\n"));
console.log(`Wrote supabase/seed.sql: ${categories.length} categories, ${products.length} products.`);
